name: env_workshop
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - numpy>=1.20
  - matplotlib>=3.4
  - opencv>=4
  - pytorch>=1.10
  - torchvision 
  - imageio
  - scikit-learn
  - jupyter
  - notebook
  - dlib
  - pip:
    - nbimporter
    - nbformat